# The following environment variables are substituted if present
# * QUORUM_CONSENSUS: default to istanbul
# * QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:2.2.3
# * QUORUM_TX_MANAGER_DOCKER_IMAGE: default to quorumengineering/tessera:0.8
version: "3.7"
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:2.2.3}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      UDS_WAIT=10
      for i in $$(seq 1 100)
      do
        set -e
        if [ -S $${PRIVATE_CONFIG} ] && \
          [ "I'm up!" == "$$(wget --timeout $${UDS_WAIT} -qO- 172.16.239.10$${NODE_ID}:9000/upcheck)" ];
        then break
        else
          echo "Sleep $${UDS_WAIT} seconds. Waiting for TxManager."
          sleep $${UDS_WAIT}
        fi
      done
      DDIR=/qdata/dd
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /nodeKeys/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /examples/keys/key$${NODE_ID}* $${DDIR}/keystore/
      cat /examples/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/examples/istanbul-genesis.json"
      if [ "${QUORUM_CONSENSUS:-istanbul}" == "raft" ]; then
        GENESIS_FILE="/examples/raft-genesis.json"
      fi
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"

      if [ ! -d $${DDIR}/geth/chaindata ]; then
        geth --datadir $${DDIR} init $${GENESIS_FILE}
      fi

      geth \
        --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpccorsdomain "*" \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
        --port 21000 \
        --unlock 0 \
        --password /examples/passwords.txt \
        $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}}
x-tx-manager-def:
  &tx-manager-def
  image: "${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.8}"
  expose:
    - "9000"
    - "9080"
    - "8082"
  restart: "no"
  healthcheck:
    test: ["CMD-SHELL", "[ -S /qdata/tm_ipc/tm.ipc ] || exit 1"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/tm
      rm -f $${DDIR}/tm.ipc
      mkdir -p $${DDIR}
      DOCKER_IMAGE="${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.8}"
      TX_MANAGER=$$(echo $${DOCKER_IMAGE} | sed 's/^.*\/\(.*\):.*$$/\1/g')
      echo "TxManager: $${TX_MANAGER}"
      case $${TX_MANAGER}
      in
        tessera)
          cp /examples/keys/tm$${NODE_ID}.pub $${DDIR}/tm.pub
          cp /examples/keys/tm$${NODE_ID}.key $${DDIR}/tm.key

          cat <<EOF > $${DDIR}/tessera-config-enhanced.json
          {
            "useWhiteList": false,
            "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./$${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
            },
            "serverConfigs":[
            {
              "app":"ThirdParty",
              "enabled": true,
              "serverSocket":{
                "type":"INET",
                "port": 9080,
                "hostName": "http://$$(hostname -i)"
              },
              "communicationType" : "REST"
            },
            {
              "app":"Q2T",
              "enabled": true,
              "serverSocket":{
                "type":"UNIX",
                "path":"$${DDIR}_ipc/tm.ipc"
              },
              "communicationType" : "UNIX_SOCKET"
            },
            {
              "app":"P2P",
              "enabled": true,
              "serverSocket":{
                "type":"INET",
                "port": 9000,
                "hostName": "http://$$(hostname -i)"
              },
              "sslConfig": {
                "tls": "OFF",
                "generateKeyStoreIfNotExisted": true,
                "serverKeyStore": "$${DDIR}/server-keystore",
                "serverKeyStorePassword": "quorum",
                "serverTrustStore": "$${DDIR}/server-truststore",
                "serverTrustStorePassword": "quorum",
                "serverTrustMode": "TOFU",
                "knownClientsFile": "$${DDIR}/knownClients",
                "clientKeyStore": "$${DDIR}/client-keystore",
                "clientKeyStorePassword": "quorum",
                "clientTrustStore": "$${DDIR}/client-truststore",
                "clientTrustStorePassword": "quorum",
                "clientTrustMode": "TOFU",
                "knownServersFile": "$${DDIR}/knownServers"
              },
              "communicationType" : "REST"
            }
            ],
            "peer": [
               {
                   "url": "http://txmanager1:9000"
               },
               {
                   "url": "http://txmanager2:9000"
               },
               {
                   "url": "http://txmanager3:9000"
               }
            ],
            "keys": {
              "passwords": [],
              "keyData": [
                {
                  "config": $$(cat $${DDIR}/tm.key),
                  "publicKey": "$$(cat $${DDIR}/tm.pub)"
                }
              ]
            },
            "alwaysSendTo": []
          }
      EOF

          java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config-enhanced.json
          ;;
        *)
          echo "Invalid Transaction Manager"
          exit 1
          ;;
      esac
services:
  node1:
    << : *quorum-def
    hostname: node1
    ports:
      - "22000:8545"
    volumes:
      - vol1:/qdata
      - ./3nodes:/examples:ro
      - ./nodeKeys:/nodeKeys
      - ./../scripts:/scripts
      - ./../testScripts:/testScripts
      - vol1_tm_ipc:/qdata/tm
    depends_on:
      - txmanager1
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=1
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.11
  txmanager1:
    << : *tx-manager-def
    hostname: txmanager1
    ports:
      - "9081:9080"
    volumes:
      - vol1_tm:/qdata/tm
      - vol1_tm_ipc:/qdata/tm_ipc
      - ./3nodes/keys:/examples/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.101
    environment:
      - NODE_ID=1
  node2:
    << : *quorum-def
    hostname: node2
    ports:
      - "22001:8545"
    volumes:
      - vol2:/qdata
      - ./3nodes:/examples:ro
      - ./nodeKeys:/nodeKeys
      - ./../scripts:/scripts
      - ./../testScripts:/testScripts
      - vol2_tm_ipc:/qdata/tm
    depends_on:
      - txmanager2
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=2
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.12
  txmanager2:
    << : *tx-manager-def
    hostname: txmanager2
    ports:
      - "9082:9080"
    volumes:
      - vol2_tm:/qdata/tm
      - vol2_tm_ipc:/qdata/tm_ipc
      - ./3nodes/keys:/examples/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.102
    environment:
      - NODE_ID=2
  node3:
    << : *quorum-def
    hostname: node3
    ports:
      - "22002:8545"
    volumes:
      - vol3:/qdata
      - ./3nodes:/examples:ro
      - ./nodeKeys:/nodeKeys
      - ./../scripts:/scripts
      - ./../testScripts:/testScripts
      - vol3_tm_ipc:/qdata/tm
    depends_on:
      - txmanager3
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=3
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.13
  txmanager3:
    << : *tx-manager-def
    hostname: txmanager3
    ports:
      - "9083:9080"
      - "8082:8082"
    volumes:
      - vol3_tm:/qdata/tm
      - vol3_tm_ipc:/qdata/tm_ipc
      - ./3nodes/keys:/examples/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.103
    environment:
      - NODE_ID=3
networks:
  quorum-examples-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
volumes:
  "vol1":
  "vol2":
  "vol3":
  "vol1_tm":
  "vol2_tm":
  "vol3_tm":
  "vol1_tm_ipc":
  "vol2_tm_ipc":
  "vol3_tm_ipc":
